# Development Dockerfile with Hot Reload
FROM node:20-alpine AS development

RUN corepack enable

WORKDIR /app

COPY package.json yarn.lock ./
COPY prisma ./prisma

RUN --mount=type=cache,target=/root/.cache/yarn \
  yarn install --frozen-lockfile

EXPOSE 3398
CMD ["yarn", "start:dev"]
